### ISSUE TITLE
error with ubuntu version in VagrantFile

### ISSUE THREAD

**Issue by pedefalco** [scriptcamp/kubeadm-scripts#3]
Hi, 
I encountered an error when trying to run the vagrant file for vm setup. This is the error

**master: E: The repository 'http://us.archive.ubuntu.com/ubuntu impish Release' no longer has a Release file.**

and the job crashed without continuing with the creation of the nodes 

I tried changing the ubuntu version, inserting an older one and everything worked correctly.

My change in vagrant file

from 
`  config.vm.box = "bento/ubuntu-21.10"`
to
`  config.vm.box = "bento/ubuntu-20.04"`

everything worked correctly.

Thanks

**Comment by scriptcamp** [comment]
@pedefalco  Issue has been fixed with bento/ubuntu-22.04
